##### COSMETICS #####
colorscheme dracula

### practical cosmetics ###
# prompt positioned at top, remove clippy art
set global ui_options ncurses_assistant=none ncurses_status_on_top=true ncurses_enable_mouse=false

# Custom title, if that ever gets implemented
#hook global WinDisplay .* %{ evaluate-commands %sh{
#    buffer=$(basename "$kak_bufname" | cat)
#    echo set-option -add buffer ui_options "'ncurses_set_title=$buffer'"
#} }

## custom modeline
# TODO: additional useful info:
# - git
# - more than one open client?
# - unsaved changes in an out-of-sight buffer?
# Shell implementation idea: Create a routine that, given a list of colors and strings, draws the bar correctly. If a string is empty, don't draw the corresponding element. Compute each string and call the routine.
set global modelinefmt '{MenuBackground} %sh{basename $kak_bufname} %val{cursor_char_column}:%val{cursor_line} %val{buf_line_count}≣ {{context_info}} {{mode_info}} [%opt{filetype}] %sh{dirname $kak_bufname} %val{session}' # 

# line numbers
add-highlighter -override global/ number-lines -hlcursor -min-digits 4 -separator " "
# highlight charlimit columns
hook global BufCreate .* %{
    add-highlighter buffer/ column 101 default,rgb:36394a
}
hook global BufSetOption filetype=(kak|markdown|gas) %{
    remove-highlighter buffer/column_101_default,rgb:36394a
    add-highlighter buffer/ column 81 default,rgb:36394a
}
# wraps lines, preserving words
#add-highlighter global/ wrap -word -indent
# show matching brackets
add-highlighter global/ show-matching
# show tabs, non-breaking spaces, etc
add-highlighter global/ show-whitespaces -spc ' ' -lf ' '
# highlight comment keywords
add-highlighter global/ regex \b(TODO|FIXME|XXX|NOTE)\b 0:default+ub
# highlight trailing whitespace
add-highlighter global/ regex \h+$ 0:Error

##### SETTINGS #####
# automatically reload files when they are modified
set-option global autoreload yes
# indent 4 chars at a time
set-option global indentwidth 4
# keep a few lines visible above/below cursor when scrolling
set-option global scrolloff 3,0

##### COMMANDS #####
# Use 'o' (open) to edit a file.
# This is mainly to avoid mistyping a `w` and destroying the file you wanted to open.
unalias global e edit
alias global o edit

##### KEYMAPS #####

# Not mapped: < > Y # ^ <del> <backspace> <ins> _ =

# Unmap the keys that have been remapped.
map global normal <gt> ''
map global normal <lt> ''
map global normal _ ''
map global normal <a-{> ''
map global normal <a-}> ''

# Change the behavior of line selection
# swap x with <a-x> so the default doesn't select the next line when standing on an empty line
# 'X' is unchanged, so holding down shift will still extend a downward
map global normal x <a-x>
map global normal <a-x> x

### Miscellaneous
map -docstring "enter LSP mode" global normal "." ": enter-user-mode lsp<ret>"
map -docstring "repeat last insert mode change" global normal <plus> .
map -docstring "unselect surrounding whitespace" global normal <minus> _

### Object selection
# TODO: Find the least-resistance way of doing object selections. Consider which selections are most common, etc.
# <Shift> is changed to mean "inner object". <Alt> is banished.
# I generally want to extend my current object selection rather than jump to the next object.
# The exception to the rule is when navigating through paragraphs, but I can just press semicolon to deselect when necessary.
map -docstring "select inner object" global normal "'" <a-i>
map -docstring "select whole object" global normal '<ret>' <a-a>
map -docstring "extend selections to whole object start" global normal [ {
map -docstring "extend selections to whole object end" global normal ] }
map -docstring "extend selections to inner object start" global normal { <a-{>
map -docstring "extend selections to inner object end" global normal } <a-}>

# we don't need three keybinds for every object to select, so we remap some selections to first-layer symbols
map -docstring "braces block" global object b B
map -docstring "paragraph" global object g p
map -docstring "parenthesis block" global object p "("

# Remove unneeded synonyms for various objects. I wish these could be properly erased.
map global object ( ''
map global object ) ''
map global object { ''
map global object } ''
map global object [ ''
map global object ] ''
map global object <lt> ''
map global object <gt> ''
map global object Q ''
map global object q ''

### Tabs
# tab indents both in normal mode and insert mode
map global normal <tab> "<gt>"
map global normal <s-tab> "<lt>"
# also indent whitespace lines in insert mode
map global insert <tab> "<a-;><a-gt>"
map global insert <s-tab> "<a-;><a-lt>"

# if a completion prompt is visible, tab will go to the next completion candidate
hook global InsertCompletionShow .* %{
    map window insert <tab> <c-n>
    map window insert <s-tab> <c-p>
}

# once the hook disappears, revert the behavior of tabs
hook global InsertCompletionHide .* %{
    unmap window insert <tab> <c-n>
    unmap window insert <s-tab> <c-p>
}

### User mappings
map -docstring "yank to clipboard" global user y "<a-|>wl-copy<ret>"
map -docstring "paste from clipboard" global user p "<a-!>wl-paste<ret>"
map -docstring "remove trailing whitespace (bufferwide)" global user w '"dZ%s +$<ret>d "dz: nop<ret>'

# spellcheck
map -docstring "highlight spelling errors" global user c ': spell<ret>'
map -docstring "clear spelling highlights" global user x ': spell-clear<ret>'
map -docstring "spelling replacement suggestions" global user r ': spell-replace<ret>'
map -docstring "jump to next spelling error" global user n ': spell-next<ret>'

# remap all regex commands to be case-insensitive by default
# inserts a small prefix that can be cancelled with <c-u>
map -docstring 'case insensitive search' global normal '/' /(?i)
map -docstring 'case insensitive backward search' global normal '<a-/>' <a-/>(?i)
map -docstring 'case insensitive extend search' global normal '?' ?(?i)
map -docstring 'case insensitive backward extend-search' global normal '<a-?>' <a-?>(?i)
map -docstring 'case insensitive select' global normal 's' s(?i)
map -docstring 'case insensitive split selections' global normal '<a-s>' S(?i)
map -docstring 'case insensitive keep selections' global normal '<a-k>' <a-k>(?i)
map -docstring 'case insensitive drop selections' global normal '<a-K>' <a-K>(?i)

# swap the keys for line splitting and regex splitting
# line splitting is ten times more useful
map -docstring "split selections on line boundaries" global normal S <a-s>


##### LANGUAGE SERVER PROTOCOL #####
eval %sh{kak-lsp --kakoune -s $kak_session}

#set-option global lsp_diagnostic_line_warning_sign " "
set-option global lsp_diagnostic_line_error_sign "→"
set-option global lsp_hover_anchor true
set-option global lsp_insert_spaces true
hook global WinSetOption filetype=(rust) %{
    lsp-enable-window
    #lsp-diagnostic-lines-disable window

    set-option global lsp_server_configuration rust.clippy_preference="on"
}

# enable semantic tokens
hook global WinSetOption filetype=(rust) %{
  hook window -group semantic-tokens BufReload .* lsp-semantic-tokens
  hook window -group semantic-tokens NormalIdle .* lsp-semantic-tokens
  hook window -group semantic-tokens InsertIdle .* lsp-semantic-tokens
  hook -once -always window WinSetOption filetype=.* %{
    remove-hooks window semantic-tokens
  }
}
