##### LANGUAGE SERVER PROTOCOL #####
# has to be placed before colorscheme for custom UI colors to work

eval %sh{kak-lsp --kakoune -s $kak_session}

declare-option -hidden str lsp_modeline_progress ""
define-command -hidden -params 6 -override lsp-handle-progress %{
    set global lsp_modeline_progress %sh{
        if ! "$6"; then
            #echo "$2${5:+" ($5%)"}${4:+": $4"}"
            echo " ${5:+"$5%"}"
        fi
    }
}

##### COSMETICS #####
colorscheme dracula

### practical cosmetics ###
# prompt positioned at top, remove clippy art, no mouse
set global ui_options terminal_assistant=none terminal_status_on_top=true terminal_enable_mouse=false
set global startup_info_version 30000000 # don't fill screen with startup info

## custom modeline
# TODO: additional useful info:
# - git
# - more than one open client?
# - unsaved changes in an out-of-sight buffer?
# Shell implementation idea: Create a routine that, given a list of colors and strings, draws the bar correctly. If a string is empty, don't draw the corresponding element. Compute each string and call the routine.

# Split file name into directory and actual file
declare-option -hidden str ml_filename
declare-option -hidden str ml_dirname
hook global WinDisplay .* %{
    set window ml_filename %sh{basename "$kak_bufname"}
    set window ml_dirname %sh{dirname "$kak_bufname"}
}

# NOTE: Avoid putting anything other than vals and opts in the modeline.
# It is re-computed *every time the cursor moves*, possibly for *every client*.
set global modelinefmt '%opt{lsp_modeline_progress} %opt{ml_filename} %val{cursor_char_column}:%val{cursor_line} %val{buf_line_count}≣ {{context_info}} {{mode_info}} [%opt{filetype}] %opt{ml_dirname} %val{session}' # 

# line numbers
add-highlighter -override global/ number-lines -hlcursor -min-digits 4 -separator "│"

# highlight current line
add-highlighter global/ line '%val{cursor_line}' default,rgb:181a26

# 100-char limit
add-highlighter global/ column 101 default,rgb:44475a

# wraps lines, preserving words
#add-highlighter global/ wrap -word -indent
# show matching brackets
add-highlighter global/ show-matching
# show tabs, non-breaking spaces, etc
add-highlighter global/ show-whitespaces -spc ' ' -lf ' '
# highlight comment keywords
add-highlighter global/ regex \b(TODO|FIXME|XXX|NOTE)\b 0:default+ub
# highlight trailing whitespace
add-highlighter global/ regex \h+$ 0:Error

##### SETTINGS #####
# remove scratch buffer message on startup
hook global BufCreate "\*scratch\*" %{
    execute-keys <percent>d
}

# automatically reload files when they are modified
set-option global autoreload yes
# indent 4 chars at a time
set-option global indentwidth 4

##### COMMANDS #####
# Use 'o' (open) to edit a file.
# This is changed to avoid mistyping a `w`
# and destroying the file you wanted to open.
unalias global e edit
alias global o edit

##### KEYMAPS #####

map global normal <a-X> Kx
map global normal X Jx

# alternative word movement
map global normal q b
map global normal Q B
map global normal <a-q> <a-b>

# to-char movement, uses f and b for forward and backward
# inclusive
map global normal f f
map global normal b <a-f>
# extend
map global normal <s-f> <s-f>
map global normal <s-b> <s-a-f>
# exclusive
map global normal <a-f> t
map global normal <a-b> <a-t>
# exclusive extend
map global normal <s-a-f> <s-t>
map global normal <s-a-b> <s-a-t>

# remap displaced macro
map global normal ` q
map global normal ~ Q

# remap displaced upper/lowercase
map global normal t `
map global normal T ~
map global normal <a-t> <a-`>

map global normal <minus> _

# swap repeat of selections with repeat of insertions
map global normal . <a-.>
map global normal <a-.> .

# tabs
set global tabstop 4

# tab indents both in normal mode and insert mode
map global normal <tab> "<gt>"
map global normal <s-tab> "<lt>"
# also indent whitespace lines in insert mode
map global insert <tab> "<a-;><a-gt>"
map global insert <s-tab> "<a-;><a-lt>"

# if a completion prompt is visible, tab will go to the next completion candidate
hook global InsertCompletionShow .* %{
    map window insert <tab> <c-n>
    map window insert <s-tab> <c-p>
}

# once the hook disappears, revert the behavior of tabs
hook global InsertCompletionHide .* %{
    unmap window insert <tab> <c-n>
    unmap window insert <s-tab> <c-p>
}

# Swap line splitting and regex splitting. Line splitting is ten times more common.
map -docstring "split selections on line boundaries" global normal S <a-s>
map -docstring "split selections with the given regex" global normal <a-s> S

# remap all regex commands to be case-insensitive by default
# inserts a small prefix that can be cancelled with <c-u>
map -docstring 'case insensitive search' global normal '/' /(?i)
map -docstring 'case insensitive backward search' global normal '<a-/>' <a-/>(?i)
map -docstring 'case insensitive extend search' global normal '?' ?(?i)
map -docstring 'case insensitive backward extend-search' global normal '<a-?>' <a-?>(?i)
map -docstring 'case insensitive select' global normal 's' s(?i)
map -docstring 'case insensitive split selections' global normal '<a-s>' S(?i)
map -docstring 'case insensitive keep selections' global normal '<a-k>' <a-k>(?i)
map -docstring 'case insensitive drop selections' global normal '<a-K>' <a-K>(?i)

##LSP
map -docstring "enable LSP" global user l ": lsp-enable-window; lsp-diagnostic-lines-disable window; set-option global lsp_hover_anchor true; set-option global lsp_insert_spaces true <ret>"
map -docstring "enter LSP mode" global normal "'" ": enter-user-mode lsp<ret>"
# separate hover info from hover diagnostics
map -docstring "show info for current position" global lsp h %{: set-option buffer lsp_show_hover_format 'printf %s "${lsp_info}"'; lsp-hover <ret>'}
map -docstring "show info for current position" global lsp e %{: set-option buffer lsp_show_hover_format 'printf %s "${lsp_diagnostics}"'; lsp-hover <ret>'}
map -docstring "show info for current position" global lsp E ': lsp-diagnostics<ret>'

### Miscellaneous
map -docstring "jump backward" global goto z "<esc><c-o>"
map -docstring "jump forward" global goto x "<esc><c-i>"

### Object selection
map -docstring "select surrounding object" global normal m <a-a>
# Inner-object selection done by pressing `m` twice
map -docstring "select inner surrounding object" global object m "<esc><a-i>"

# we don't need three keybinds for every object to select,
# so we remap some selections to first-layer symbols
map -docstring "braces block" global object b B
map -docstring "sentence" global object . s
map -docstring "double quoted string" global object q Q

### User mappings
map -docstring "yank to clipboard" global user y "<a-|>wl-copy<ret>"
map -docstring "paste from clipboard" global user p "<a-!>wl-paste<ret>"
map -docstring "remove trailing whitespace (bufferwide)" global user w '"dZ%s +$<ret>d"dz'

# spellcheck
map -docstring "highlight spelling errors" global user c ': spell<ret>'
map -docstring "clear spelling highlights" global user x ': spell-clear<ret>'
map -docstring "spelling replacement suggestions" global user r ': spell-replace<ret>'
map -docstring "jump to next spelling error" global user n ': spell-next<ret>'
